quotes/urls.py
# from django.contrib import admin
from django.urls import path
from . import views
from .views import author_detail, tag_detail, top_tags

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="main"),
    path("<int:page>", views.main, name="root_paginate"),
    path('tag/<str:tag_name>/', tag_detail, name='tag_detail'),
    path('tag/<str:tag_name>/<int:page>/', tag_detail, name='tag_detail_paginated'),
    path('author/<str:author_name>/', author_detail, name='author_detail'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('top_tags/', top_tags, name='top_tags'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

web_hw10_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path('users/', include('users.urls')),
]

models.py
# models.py
from mongoengine import Document, StringField, ReferenceField, ListField

class Author(Document):
    fullname = StringField(max_length=50)
    born_date = StringField(max_length=50)
    born_location = StringField(max_length=150)
    description = StringField()
    created_at = StringField()

class Tag(Document):
    name = StringField(max_length=50, required=True, unique=True)

class Quote(Document):
    quote = StringField()
    tags = ListField(ReferenceField(Tag))
    author = ReferenceField(Author)
    created_at = StringField()

quotes/models.py
from django.db import models
from django.db.models import F
from django.db.models import Sum


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    popularity = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    @classmethod
    def update_popularity(cls):
        # Обновляем популярность тегов
        tags_with_popularity = cls.objects.annotate(tag_popularity=Sum('quote__popularity'))
        for tag in tags_with_popularity:
            cls.objects.filter(id=tag.id).update(popularity=F('tag_popularity'))

class Quote(models.Model):

    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models

# Create your models here.

quotes/forms.py
from django import forms
from .models import Author, Quote, Tag


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Quote, Author, Tag
from .forms import AuthorForm, QuoteForm
from django.db.models import F

# Create your views here.
def main(request, page=1):
    per_page = 10
    quotes = Quote.objects.all()
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

def author_detail(request, author_name):
    authors = Author.objects.filter(fullname=author_name)
    
    if not authors.exists():
        # Обработка случая, когда автор не найден
        return render(request, 'quotes/author_not_found.html', {'author_name': author_name})
    
    author = authors.first()

    return render(request, 'quotes/author_detail.html', {'author': author})

def tag_detail(request, tag_name):
    quotes_list = Quote.objects.filter(tags__name=tag_name)
    paginator = Paginator(quotes_list, 10)
    
    page = request.GET.get('page')
    quotes = paginator.get_page(page)
    
    context = {'tag': tag_name, 'quotes': quotes}
    return render(request, 'quotes/tag_detail.html', context)

def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save()
            return redirect('quotes:author_detail', author_name=author.fullname)
    else:
        form = AuthorForm()

    return render(request, 'quotes/add_author.html', {'form': form})

def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quotes:main')
    else:
        form = QuoteForm()

    all_tags = Tag.objects.all()
    all_authors = Author.objects.all()

    return render(request, 'quotes/add_quote.html', {'form': form, 'all_tags': all_tags, 'all_authors': all_authors})


def top_tags(request):
    # Обновляем популярность тегов
    update_tags_popularity()

    # Получаем 10 самых популярных тегов
    top_tags = Tag.objects.order_by('-popularity')[:10]

    # Возвращаем шаблон с данными
    return render(request, 'quotes/top_tags.html', {'top_tags': top_tags})

def update_tags_popularity():
    # Очищаем популярность у всех тегов перед обновлением
    Tag.objects.all().update(popularity=0)

    # Обновляем популярность тегов на основе цитат
    for quote in Quote.objects.all():
        for tag in quote.tags.all():
            Tag.objects.filter(name=tag.name).update(popularity=F('popularity') + 1)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
       return redirect(to='quotes:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:main')

quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="container">
    <h2>Add Author</h2>

    <form method="post" action="{% url 'quotes:add_author' %}">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="fullname">Full Name:</label>
            <input type="text" name="fullname" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="born_date">Born Date:</label>
            <input type="text" name="born_date" class="form-control">
        </div>

        <div class="form-group">
            <label for="born_location">Born Location:</label>
            <input type="text" name="born_location" class="form-control">
        </div>

        <div class="form-group">
            <label for="description">Description:</label>
            <textarea name="description" class="form-control" rows="4"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Add Author</button>
    </form>
</div>

{% endblock %}

quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="container">
    <h2>Add Quote</h2>

    <form method="post" action="{% url 'quotes:add_quote' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Quote</button>
    </form>
</div>

{% endblock %}

quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}
{% block content %}

<div class="author-detail">
    <h2>{{ author.fullname }}</h2>
    <p>Born: {{ author.born_date }} in {{ author.born_location }}</p>
    <p>{{ author.description }}</p>
    <!-- Другие детали об авторе, которые вы хотите отобразить -->

    <!-- Добавьте цитаты этого автора, если нужно -->
    {% if author.quote_set.all %}
        <h3>Quotes by {{ author.fullname }}</h3>
        <ul>
            {% for quote in author.quote_set.all %}
                <li>{{ quote.quote }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

{% endblock %}

quotes/templates/quotes/author_not_found.html
{% extends 'quotes/base.html' %}
{% block content %}

    <h1>Author Not Found</h1>
    <p>The author "{{ author_name }}" was not found.</p>
    <a href="{% url 'quotes:root' %}">Go back to the main page</a>

{% endblock %}

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Quotes</title>
</head>

<body>

    <div class="container">

        <div class="row header-box">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>    
        </div>

        {% block content %} {% endblock %}

    </div>
</body>

</html>

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

    <div class="col-md-6">
        <a href="{% url 'quotes:top_tags' %}" class="btn btn-primary">Top Ten tags</a>
        <div class="d-flex justify-content-end">
            
            {% if user.is_authenticated %}
                <div class="ml-auto">
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote</a>
                </div>
                <li>Welcome <b>{{ user.username }}!</b>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary ml-2">Logout</a></li>
            {% else %}
                <div>
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary ml-2">Login</a>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            {% for quote in quotes %}
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">{{ quote.quote }}</span>
                <span class="author">
                    by <a href="{% url 'quotes:author_detail' quote.author.fullname %}">{{ quote.author.fullname }}</a> 
                    (<a href="{% url 'quotes:author_detail' quote.author.fullname %}">about</a>)
                </span>
                <br>
                <span class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                        <a class="tag" href="{% url 'quotes:tag_detail' tag.name %}">{{ tag.name }}</a>
                    {% endfor %}
                </span>
            </div>
            {% endfor %}
            <nav>
                <ul class="pager">
                    <li class="previous">
                        <a class="{% if not quotes.has_previous %}disabled invisible{% endif %}"
                           href="{% if quotes.has_previous %}{% url 'quotes:root_paginate' quotes.previous_page_number %}{% else %}#{% endif %}">
                            <span aria-hidden="true">←</span> Previous
                        </a>
                    </li>
                    <li class="next">
                        <a class="{% if not quotes.has_next %}disabled invisible{% endif %}"
                           href="{% if quotes.has_next %}{% url 'quotes:root_paginate' quotes.next_page_number %}{% else %}#{% endif %}">
                            Next <span aria-hidden="true">→</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    
{% endblock %}

quotes/templates/quotes/tag_detail.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<h1>Quotes with Tag: {{ tag.name }}</h1>

<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{ quote.quote }}</span>
        <span class="author">
            by <a href="{% url 'quotes:author_detail' quote.author.fullname %}">{{ quote.author.fullname }}</a> 
            (<a href="{% url 'quotes:author_detail' quote.author.fullname %}">about</a>)
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="{% url 'quotes:tag_detail' tag.name %}">{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled invisible {% endif %}"
                   href="{% if quotes.has_previous %}?page={{ quotes.previous_page_number }}{% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            <li class="next">
                {% if quotes.has_next %}
                    <a href="?page={{ quotes.next_page_number }}">
                        Next <span aria-hidden="true">→</span>
                    </a>
                {% else %}
                    <span class="disabled invisible">Next <span aria-hidden="true">→</span></span>
                {% endif %}
            </li>
        </ul>
    </nav>  
    </div>
</div>

{% endblock %}

quotes/templates/quotes/top_tags.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h2>Top Ten tags</h2>
    
    <ul>
        {% for tag in top_tags %}
            <li>
                <a href="{% url 'quotes:tag_detail' tag.name %}">{{ tag.name }}</a>
                ({{ tag.popularity }})
            </li>
        {% endfor %}
    </ul>
{% endblock %}

users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}